version: "3.8"
volumes:
    db:
    backups:
networks:
    net:
        attachable: false
services:
    db:
        image: postgres:14
        volumes:
            - db:/var/lib/postgresql/
        networks:
            - net
        env_file:
            - ./backend/.env_prod
        restart: on-failure
    app:
        depends_on:
            - db
        build: ./
        working_dir: /app/
        volumes:
            - backups:/app/backend/backups/
            - C:/Users/anand/Desktop/reddit_expanse/raw_json:/raw_json
        networks:
            - net
        ports:
            - "1301:1301"
        environment:
            - VERSION=1.2.9
        env_file:
            - ./backend/.env_prod
        entrypoint: []
        command: sh -c "cd ./backend/ && npm run prod"
        restart: on-failure
